name: freetimemaker-cat
base: core24
version: '1.0.1'
summary: Clicker but you click Cats
description: |
  Like said in the summary, it's a Clicker Game where you have to click on Cats.

grade: stable
confinement: strict  # 'strict' wird empfohlen, classic ist nicht erlaubt mit core24

parts:
  freetimemaker-plc:
    plugin: dump
    source: snap/local
    organize:
      share/applications/freetimemaker-plc.desktop: usr/share/applications/freetimemaker-cat.desktop
      share/icons/hicolor/128x128/apps/freetimemaker-plc.png: meta/gui/freetimemaker-cat.png

apps:
  freetimemaker-plc:
    command: Cat Clicker.x86_64
    extensions: [gnome]
    environment:
      LD_LIBRARY_PATH: "$SNAP/Cat Clicker_Data/Plugins/x86_64:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$LD_LIBRARY_PATH"
    plugs:
      - x11
      - opengl
      - network
      - network-bind
      - audio-playback
      - joystick
      - home

